# Generated by Django 5.2.15 on 2026-07-01 08:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models

import mapentity.models


class Migration(migrations.Migration):
    dependencies = [
        ("test_shapes", "0002_alter_geometrycollectionmodel_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedTypesModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                "verbose_name": "AllowedTypes Model",
                "verbose_name_plural": "AllowedTypes Models",
            },
            bases=(mapentity.models.DuplicateMixin, models.Model),
        ),
    ]
