"""
Django settings for test_project project.

Generated by 'django-admin startproject' using Django 1.8.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
from tempfile import TemporaryDirectory

from django.contrib import messages

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "37r=l^!c^1-7o8z2luc%a1x&)jt^9v+ockis0ql7k_y*lm555("
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = (
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "debug_toolbar",
    "paperclip",
    "compressor",
    "easy_thumbnails",
    "django_filters",
    "crispy_forms",
    "crispy_bootstrap4",
    "rest_framework",
    "embed_video",
    "tinymce",
    "mapbox_baselayer",
    "mapentity",  # Make sure mapentity settings are loaded before leaflet ones
    "test_project.test_app",
    "test_project.test_shapes",
    "modeltranslation",
)

MIDDLEWARE = (
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "mapentity.middleware.AutoLoginMiddleware",
)


ROOT_URLCONF = "test_project.urls"

TEMPLATES = [
    {
        "BACKEND": "djappypod.backend.OdtTemplates",
    },
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "mapentity.context_processors.settings",
            ],
        },
    },
]

WSGI_APPLICATION = "test_project.wsgi.application"
INTERNAL_IPS = type("c", (), {"__contains__": lambda *a: True})()

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.spatialite",
        "NAME": os.path.join(BASE_DIR, "database.db"),
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGES = (
    ("en", "English"),
    ("fr", "French"),
)

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "test_project", "static"),
]

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}
# VECTOR_TILES_BACKEND = "vectortiles.backends.python"
MEDIA_URL = "/media/"
MEDIA_URL_SECURE = "/media_secure/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

SRID = 4326
COMPRESS_ENABLED = False
TEST = True

# MAPENTITY_CONFIG = {
#     'SENDFILE_HTTP_HEADER': 'X-Accel-Redirect',
# }

PAPERCLIP_FILETYPE_MODEL = "test_app.FileType"
PAPERCLIP_LICENSE_MODEL = "test_app.License"
PAPERCLIP_ATTACHMENT_MODEL = "test_app.Attachment"

if os.path.exists("/usr/lib/x86_64-linux-gnu/mod_spatialite.so"):
    SPATIALITE_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu/mod_spatialite"


MAPLIBRE_CONFIG_OVERRIDES = {
    "DEFAULT_CENTER": [1.3952, 43.5963],  # Toulouse, France
    "DEFAULT_ZOOM": 5,
    "SCALE": "metric",
    "BOUNDS": [[-5.5, 40.120372], [10, 52]],
}


DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

MAPENTITY_CONFIG = {
    "CONVERSION_SERVER": "http://convertit:6543",
    "CAPTURE_SERVER": "http://screamshotter:8000",
    "SENDFILE_HTTP_HEADER": "X-Accel-Redirect",
    "MAP_STYLES": {
        "dummymodel": {
            "weight": 3,
            "opacity": 0.5,
            "color": "green",
        },
        "road": {
            "weight": 6,
            "opacity": 1,
            "color": "red",
            "arrowColor": "#FF5E00",
            "arrowSize": 8,
        },
        "singlelinestringmodel": {
            "weight": 10,
            "opacity": 1,
            "color": "yellow",
            "arrowColor": "#FF5E00",
        },
    },
}
LOCALE_PATHS = (os.path.join(BASE_DIR, "test_project", "locale"),)
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"

MODELTRANSLATION_LANGUAGES = ("en", "fr", "zh-hant")

if "test" in sys.argv:
    MEDIA_ROOT = TemporaryDirectory().name


POPUP_CONTENT = {
    "dummymodel": ["short_description", "public", "tags", "name", "test"],
}

MESSAGE_TAGS = {
    messages.SUCCESS: "alert-success",
    messages.INFO: "alert-info",
    messages.DEBUG: "alert-info",
    messages.WARNING: "alert-warning",
    messages.ERROR: "alert-danger",
}
