from .api import MapEntityViewSet
from .base import (
    JSSettings,
    ServeAttachment,
    history_delete,
    map_screenshot,
)
from .generic import (
    Convert,
    DocumentConvert,
    MapEntityCreate,
    MapEntityDelete,
    MapEntityDetail,
    MapEntityDocument,
    MapEntityDocumentBase,
    MapEntityDocumentOdt,
    MapEntityDocumentWeasyprint,
    MapEntityDuplicate,
    MapEntityFilter,
    MapEntityFormat,
    MapEntityList,
    MapEntityMapImage,
    MapEntityMarkupWeasyprint,
    MapEntityUpdate,
)
from .logentry import LogEntryList, LogEntryViewSet
from .mixins import (
    HttpJSONResponse,
    JSONResponseMixin,
    LastModifiedMixin,
    ModelViewMixin,
)

MAPENTITY_GENERIC_VIEWS = [
    MapEntityList,
    MapEntityFilter,
    MapEntityFormat,
    MapEntityMapImage,
    MapEntityDocument,
    MapEntityMarkupWeasyprint,
    MapEntityCreate,
    MapEntityDuplicate,
    MapEntityDetail,
    MapEntityUpdate,
    MapEntityDelete,
]

__all__ = [
    "Convert",
    "MapEntityList",
    "MapEntityFilter",
    "MapEntityFormat",
    "MapEntityMapImage",
    "MapEntityDocument",
    "MapEntityDocumentBase",
    "MapEntityDocumentOdt",
    "MapEntityDocumentWeasyprint",
    "MapEntityMarkupWeasyprint",
    "DocumentConvert",
    "MapEntityCreate",
    "MapEntityDuplicate",
    "MapEntityDetail",
    "MapEntityUpdate",
    "MapEntityDelete",
    "MapEntityViewSet",
    "HttpJSONResponse",
    "JSONResponseMixin",
    "LastModifiedMixin",
    "ModelViewMixin",
    "MAPENTITY_GENERIC_VIEWS",
    "ServeAttachment",
    "JSSettings",
    "map_screenshot",
    "history_delete",
    "LogEntryList",
    "LogEntryViewSet",
]
