# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='tags',
            field=models.ManyToManyField(to='test_app.Tag'),
        ),
    ]
