# Generated by Django 3.1.4 on 2020-12-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20180504_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_image',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='Is an image file', verbose_name='Is image'),
        ),
    ]
