# Generated by Django 3.1.4 on 2020-12-10 09:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_attachment_is_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(spatial_index=False, srid=2154)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
