# Generated by Django 3.1.4 on 2020-12-10 10:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AnyGeomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=2154)),
                ('tags', models.ManyToManyField(blank=True, related_name='whatevergeoms', to='test_app.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
