# Generated by Django 3.1.4 on 2020-12-10 16:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_anygeommodel_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(spatial_index=False, srid=2154)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('geom', django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326)),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='Begin date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('themes', models.ManyToManyField(blank=True, help_text='Main theme(s)', related_name='events', to='test_app.Theme', verbose_name='Themes')),
            ],
            options={
                'verbose_name': 'Event',
            },
        ),
    ]
