# Generated by Django 3.2.10 on 2021-12-08 09:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(default=None, null=True, srid=2154)),
                ('parking', django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=2154)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
