# Generated by Django 4.0.4 on 2022-04-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_dummymodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='author',
            field=models.CharField(blank=True, default='', help_text='Original creator', max_length=128, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='legend',
            field=models.CharField(blank=True, default='', help_text='Details displayed', max_length=128, verbose_name='Legend'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='starred',
            field=models.BooleanField(default=False, help_text='Mark as starred', verbose_name='Starred'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Renames the file', max_length=128, verbose_name='Filename'),
        ),
    ]
