# Generated by Django 3.2.12 on 2022-03-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_dummymodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='name',
            field=models.CharField(default='Empty', max_length=100),
        ),
    ]
