# Generated by Django 3.1.4 on 2020-12-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_auto_20201221_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='geom',
        ),
    ]
