# Generated by Django 3.2.13 on 2022-04-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_merge_20220412_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummymodel',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='Short description'),
        ),
    ]
