# Generated by Django 3.2.11 on 2022-04-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_merge_20220412_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True, verbose_name='License name')),
            ],
            options={
                'verbose_name': 'Attachment license',
                'verbose_name_plural': 'Attachment licenses',
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.license', verbose_name='License'),
        ),
    ]
