# Generated by Django 3.1.4 on 2020-12-22 08:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_remove_event_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(default=None, null=True, srid=2154),
        ),
    ]
