# Generated by Django 3.2.13 on 2022-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_auto_20220427_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummymodel',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='Short description'),
        ),
    ]
