# Generated by Django 3.2.11 on 2022-12-21 14:13

from django.db import migrations, models
import django.db.models.deletion
import mapentity.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_dummymodel_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummymodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='test_app.Tag'),
        ),
        migrations.CreateModel(
            name='ManikinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manikins', to='test_app.dummymodel')),
            ],
            options={
                'abstract': False,
            },
            bases=(mapentity.models.DuplicateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummies', models.ManyToManyField(to='test_app.DummyModel')),
            ],
            options={
                'abstract': False,
            },
            bases=(mapentity.models.DuplicateMixin, models.Model),
        ),
    ]
