# Generated by Django 3.2.11 on 2023-01-10 14:05

from django.db import migrations, models

import mapentity.models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0013_auto_20221221_1413"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "code",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=(mapentity.models.DuplicateMixin, models.Model),
        ),
    ]
