# Generated by Django 4.2.6 on 2023-10-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_auto_20230215_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='name_en',
            field=models.CharField(default='Empty', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='name_fr',
            field=models.CharField(default='Empty', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='name_zh_hant',
            field=models.CharField(default='Empty', max_length=100, null=True),
        ),
    ]
