# Generated by Django 4.2.20 on 2025-06-17 08:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import mapentity.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0017_road_name_en_road_name_fr_road_name_zh_hant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyAptModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('name_en', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('name_fr', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('name_zh_hant', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('short_description', models.TextField(blank=True, default='', help_text='Short description')),
                ('description', models.TextField(blank=True, default='')),
                ('geom', django.contrib.gis.db.models.fields.GeometryCollectionField(default=None, null=True, srid=4326)),
                ('date_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('public', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, to='test_app.tag')),
            ],
            options={
                'verbose_name': 'DummyApt Model',
            },
            bases=(mapentity.models.DuplicateMixin, models.Model),
        ),
    ]
