# Generated by Django 4.2.26 on 2025-12-08 15:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import mapentity.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('test_app', '0017_road_name_en_road_name_fr_road_name_zh_hant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('public_en', models.BooleanField(default=False)),
                ('public_fr', models.BooleanField(default=False)),
                ('public_zh_hant', models.BooleanField(default=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('name_zh_hant', models.CharField(max_length=255, null=True)),
                ('internal_reference', models.CharField(editable=False, max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('located_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.city')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.sector')),
                ('tags', models.ManyToManyField(to='test_app.tag')),
                ('weather_station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.weatherstation')),
            ],
            options={
                'abstract': False,
            },
            bases=(mapentity.models.DuplicateMixin, models.Model),
        ),
    ]
