# Generated by Django 4.2.26 on 2025-11-14 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0017_road_name_en_road_name_fr_road_name_zh_hant"),
    ]

    operations = [
        migrations.AddField(
            model_name="road",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="test_app.tag",
            ),
        ),
    ]
