# Generated by Django 4.2.27 on 2026-01-09 10:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models

import mapentity.models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("test_app", "0018_dummyaptmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoPoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public", models.BooleanField(default=False)),
                ("public_en", models.BooleanField(default=False)),
                ("public_fr", models.BooleanField(default=False)),
                ("public_zh_hant", models.BooleanField(default=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        default=None, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_fr", models.CharField(max_length=255, null=True)),
                ("name_zh_hant", models.CharField(max_length=255, null=True)),
                ("internal_reference", models.CharField(editable=False, max_length=20)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "dummy_model",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_app.dummymodel",
                    ),
                ),
                (
                    "located_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test_app.city",
                    ),
                ),
                (
                    "road",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="test_app.road"
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="test_app.tag")),
            ],
            options={
                "abstract": False,
            },
            bases=(mapentity.models.DuplicateMixin, models.Model),
        ),
    ]
