# Generated by Django 4.2.27 on 2025-12-22 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0018_geopoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geopoint',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='geopoint',
            name='weather_station',
        ),
        migrations.AddField(
            model_name='geopoint',
            name='dummy_model',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.dummymodel'),
        ),
        migrations.AddField(
            model_name='geopoint',
            name='road',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_app.road'),
            preserve_default=False,
        ),
    ]
