# Generated by Django 4.2.27 on 2026-01-29 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0019_geopoint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mushroomspot",
            options={
                "verbose_name": "Mushroom Spot",
                "verbose_name_plural": "Mushroom Spots",
            },
        ),
    ]
