# Generated by Django 4.2.27 on 2025-12-22 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("test_app", "0019_remove_geopoint_sector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geopoint",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="geopoint",
            name="tags",
            field=models.ManyToManyField(blank=True, to="test_app.tag"),
        ),
    ]
