# Generated by Django 4.2.27 on 2026-01-09 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0018_road_tag"),
        ("test_app", "0020_alter_geopoint_content_type_alter_geopoint_tags"),
    ]

    operations = []
