# Generated by Django 4.2.27 on 2026-02-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0020_alter_mushroomspot_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mushroomspot",
            name="tags",
            field=models.ManyToManyField(blank=True, to="test_app.tag"),
        ),
    ]
