# Generated by Django 4.2.28 on 2026-02-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0021_alter_mushroomspot_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "City", "verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="dummymodel",
            options={
                "verbose_name": "Dummy Model",
                "verbose_name_plural": "Dummy Models",
            },
        ),
        migrations.AlterModelOptions(
            name="supermarket",
            options={
                "verbose_name": "Supermarket",
                "verbose_name_plural": "Supermarkets",
            },
        ),
        migrations.AddField(
            model_name="supermarket",
            name="name",
            field=models.CharField(default="test", max_length=100, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="dummyaptmodel",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="dummyaptmodel",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=128, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="dummyaptmodel",
            name="name_fr",
            field=models.CharField(
                blank=True, default="", max_length=128, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="dummyaptmodel",
            name="name_zh_hant",
            field=models.CharField(
                blank=True, default="", max_length=128, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="dummymodel",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="dummymodel",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=128, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="dummymodel",
            name="name_fr",
            field=models.CharField(
                blank=True, default="", max_length=128, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="dummymodel",
            name="name_zh_hant",
            field=models.CharField(
                blank=True, default="", max_length=128, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="geopoint",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="geopoint",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="geopoint",
            name="name_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="geopoint",
            name="name_zh_hant",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="mushroomspot",
            name="name",
            field=models.CharField(
                default="Empty", max_length=100, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="name",
            field=models.CharField(
                default="Empty", max_length=100, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="name_en",
            field=models.CharField(
                default="Empty", max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="name_fr",
            field=models.CharField(
                default="Empty", max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="name_zh_hant",
            field=models.CharField(
                default="Empty", max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
    ]
