# Generated by Django 4.2.28 on 2026-02-04 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("test_app", "0022_alter_city_options_alter_dummymodel_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GeoPoint",
            new_name="ComplexModel",
        ),
        migrations.AlterModelOptions(
            name="complexmodel",
            options={
                "verbose_name": "Complex Model",
                "verbose_name_plural": "Complex Models",
            },
        ),
        migrations.DeleteModel(
            name="DummyAptModel",
        ),
    ]
