# Generated by Django 4.2.28 on 2026-02-04 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0023_rename_geopoint_complexmodel_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="road",
            options={"verbose_name": "Road", "verbose_name_plural": "Roads"},
        ),
    ]
