# Generated by Django 4.2.28 on 2026-02-05 16:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models

import mapentity.models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0024_alter_road_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="HiddenModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        default=None, null=True, srid=2154
                    ),
                ),
            ],
            options={
                "verbose_name": "Hidden Model",
                "verbose_name_plural": "Hidden Models",
            },
            bases=(mapentity.models.DuplicateMixin, models.Model),
        ),
    ]
