# Generated by Django 4.2.28 on 2026-02-05 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0025_add_hiddenmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Supermarket",
        ),
    ]
