# Generated by Django 5.2.11 on 2026-02-11 08:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models

import mapentity.models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0026_delete_supermarket"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiGeomModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(
                        default=None, null=True, srid=2154
                    ),
                ),
                (
                    "parking",
                    django.contrib.gis.db.models.fields.PointField(
                        default=None, null=True, srid=2154
                    ),
                ),
                (
                    "points",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        default=None, null=True, srid=2154
                    ),
                ),
            ],
            options={
                "verbose_name": "Multi Geom Model",
                "verbose_name_plural": "Multi Geom Models",
            },
            bases=(mapentity.models.DuplicateMixin, models.Model),
        ),
    ]
