# Generated by Django 5.2.11 on 2026-02-12 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0027_multigeommodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multigeommodel",
            name="geom",
        ),
    ]
