# Generated by Django 5.2.11 on 2026-02-15 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0028_complexmodel_created_at_complexmodel_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="road",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="road",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
