# Generated by Django 5.2.11 on 2026-02-12 20:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0028_remove_multigeommodel_geom"),
    ]

    operations = [
        migrations.AddField(
            model_name="multigeommodel",
            name="geom",
            field=django.contrib.gis.db.models.fields.GeometryField(
                default=None, null=True, srid=2154
            ),
        ),
    ]
