# Generated by Django 5.2.11 on 2026-02-17 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0029_road_created_at_road_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complexmodel",
            old_name="updated_at",
            new_name="date_update",
        ),
        migrations.RenameField(
            model_name="road",
            old_name="updated_at",
            new_name="date_update",
        ),
    ]
