# Generated by Django 5.2.11 on 2026-02-23 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0031_multigeommodel_date_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="road",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="test_app.tag",
            ),
        ),
    ]
