# Generated by Django 3.2.13 on 2022-06-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapentity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'permissions': (('read_logentry', 'Can read log entries'),)},
        ),
    ]
